spring:
  application:
    name: member-service

datasource:
  url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  driver-class-name: org.h2.Driver
  username: sa
  password:

  hikari:
    minimum-idle: 5
    maximum-pool-size: 20
    idle-timeout: 30000 # 30 seconds
    max-lifetime: 1800000 # 30 minutes
    connection-timeout: 20000 # 20 seconds
    validation-timeout: 5000 # 5 seconds

jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  hibernate:
    ddl-auto: create-drop
  properties:
    hibernate:
      format_sql: true
      show-sql: true
      generate_statistics: true
      dialect: org.hibernate.dialect.H2Dialect
      default_schema: MEMBER_MGMT
  sql:
    init:
      mode: never
  flyway:
    enabled: false

cache:
  type: simple

jwt:
  secret: "test-jwt-secret-key-for-unit-testing-only-12345"
  expiration: 3600000

server:
  port: 8090

logging:
  level:
    root: INFO
    com.surest.member_service: DEBUG
  file:
    name: logs/application.log

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui