spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/surest-db
    username: postgres
    password: Evry@123
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000 # 30 seconds
      max-lifetime: 1800000 # 30 minutes
      connection-timeout: 20000 # 20 seconds
      validation-timeout: 5000 # 5 seconds
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    dialect: org.hibernate.dialect.PostgresSQLDialect
    format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

cache:
  type: simple

jwt:
  secret: my-super-secret-key-that-is-long-enough-1234567890!@#
  expiration-time: 3600000

logging:
  level:
    root: INFO
    com.surest.member_service: DEBUG
  file:
    name: logs/application.log

server:
  port: 8090

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
